all: secretSharing.o
	                g++ -o secretSharing secretSharing.o
secretSharing.o: secretSharing.cpp
	                g++ -c secretSharing.cpp -std=c++14
clean:
	                rm -rf *.o secretSharing
